=== Ihorko-bk/task13_XML/src/main/resources/xml/flowers.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="flowers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="flower" type="flowerType" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="flowerType">
        <xsd:sequence>

            <xsd:element name="name" type="xsd:string"/>

            <xsd:element name="soil">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="підзолиста"/>
                        <xsd:enumeration value="ґрунтова"/>
                        <xsd:enumeration value="дерново-підзолиста"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

            <xsd:element name="origin" type="xsd:string"/>

            <xsd:element name="visual_parameters">
                <xsd:complexType>
                    <xsd:sequence>

                        <xsd:element name="stem_color" type="xsd:string"/>

                        <xsd:element name="leaf_color" type="xsd:string"/>

                        <xsd:element name="plant_average_size">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:decimal">
                                    <xsd:minInclusive value="0.1"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>

                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="growing_tips">
                <xsd:complexType>
                    <xsd:sequence>

                        <xsd:element name="temperature">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:decimal">
                                    <xsd:minExclusive value="0.0"/>
                                    <xsd:maxInclusive value="75.0"/>
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:element>

                        <xsd:element name="light" type="xsd:boolean"/>

                        <xsd:element name="watering" type="xsd:int"/>

                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="multiplying">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="листками"/>
                        <xsd:enumeration value="живцями"/>
                        <xsd:enumeration value="насінням"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>

        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== Ihorko-bk/task13_XML/src/main/resources/xml/flowers.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="flowers.xsl"?>

<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="flowers.xsd">
    <flower>
        <name>Рослина1</name>
        <soil>дерново-підзолиста</soil>
        <origin>Якесь місце походження рослини</origin>
        <visual_parameters>
            <stem_color>зелений</stem_color>
            <leaf_color>червоний</leaf_color>
            <plant_average_size>10</plant_average_size>
        </visual_parameters>
        <growing_tips>
            <temperature>30</temperature>
            <light>true</light>
            <watering>1000</watering>
        </growing_tips>
        <multiplying>живцями</multiplying>
    </flower>
    <flower>
        <name>Квітка</name>
        <soil>ґрунтова</soil>
        <origin>Україна</origin>
        <visual_parameters>
            <stem_color>зелений</stem_color>
            <leaf_color>червоний</leaf_color>
            <plant_average_size>40</plant_average_size>
        </visual_parameters>
        <growing_tips>
            <temperature>25</temperature>
            <light>true</light>
            <watering>500</watering>
        </growing_tips>
        <multiplying>насінням</multiplying>
    </flower>
    <flower>
        <name>nn</name>
        <soil>дерново-підзолиста</soil>
        <origin>aaa</origin>
        <visual_parameters>
            <stem_color>asd</stem_color>
            <leaf_color>asd</leaf_color>
            <plant_average_size>1</plant_average_size>
        </visual_parameters>
        <growing_tips>
            <temperature>11</temperature>
            <light>true</light>
            <watering>333</watering>
        </growing_tips>
        <multiplying>насінням</multiplying>
    </flower>

</flowers>
